In [1]:
import cv2
import numpy as np

In [2]:
arr = np.array([[0, 0, 0, 0, 0], [0, 125, 125, 125, 0], [0, 125, 125, 125, 0], [0, 125, 125, 125, 0], [0, 0, 0, 0, 0]])

# arr = np.array([[0, 0, 0, 0], [0, 125, 125, 0], [0, 125, 125, 0], [0, 0, 0, 0]])

# arr = np.array([[0,0,0], [0, 125, 0], [0, 0, 0]])
arr, len(arr)

(array([[  0,   0,   0,   0,   0],
        [  0, 125, 125, 125,   0],
        [  0, 125, 125, 125,   0],
        [  0, 125, 125, 125,   0],
        [  0,   0,   0,   0,   0]]), 5)

In [3]:
#Row Projection
r_p = []

for i in range(len(arr)):
    r_p.append(np.sum(arr[i]))

print("Row Projection: ", end='')
print(r_p)

Row Projection: [0, 375, 375, 375, 0]


In [4]:
#Column projection
c_p = []

for i in range(len(arr)):
    tmp = []
    for j in range(len(arr[i])):
        tmp.append(arr[j][i])

    c_p.append(sum(tmp))

print("Column Projection: ", end='')
print(c_p)

Column Projection: [0, 375, 375, 375, 0]


In [5]:
#45 degree projection

d45_p = []

d45_p = [0 for i in range(len(arr)+len(arr[0])-1)]

for i in range(len(arr)):
    for j in range(len(arr[i])):
        #print(i, j)
        d45_p[i+j] += arr[i][j]


print("45 Degree dDagonal Projection: ", end='')
print(d45_p)

45 Degree dDagonal Projection: [0, 0, 125, 250, 375, 250, 125, 0, 0]


In [6]:
#135 degree projection

d135_p = []

sum_first = []
sum_second = []
start = len(arr[0])-1

# print("start: " + str(start))

# for k in range((2*len(arr)-1)//2):
#     tmp_sum = 0
#     tmp_sum_opp = 0
#     for i in range(len(arr)):
#         for j in range(len(arr[i])):
#             if(i<j):
#                 #print(i, j)
#                 temp = i
#                 temp2 = j
#                 while(temp<len(arr) and temp2<len(arr[0])):
#                     print(temp, temp2)
#                     temp += 1
#                     temp2 += 1
                

# for k in range((2*len(arr)-1)//2):
#     tmp_sum = 0
#     tmp_sum_opp = 0
#     for i in range(len(arr)):
#         for j in range(len(arr[i])):
#             temp = i
#             temp2 = j
#             while(temp<len(arr)):
            
    
# for i in range(len(arr)):
for j in range(len(arr[0])):
    tmp_sum = 0
    tmp_sum_opp = 0
    temp = 0
    temp2 = j
    if(temp<=temp2):
        while(temp<len(arr) and temp2<len(arr[0])):
            print(temp, temp2)
            
            tmp_sum += arr[temp][temp2]
            tmp_sum_opp += arr[temp2][temp]
            
            temp += 1
            temp2 += 1
        #print(tmp_sum, tmp_sum_opp)
        sum_first.append(tmp_sum)
        sum_second.append(tmp_sum_opp)



print(sum_first)
print(sum_second)
d135_p = sum_first[::-1]
for i in range(1, len(sum_second)):
    d135_p.append(sum_second[i])

print("135 Degree Diagonal Projection: ", end='')
print(d135_p)

0 0
1 1
2 2
3 3
4 4
0 1
1 2
2 3
3 4
0 2
1 3
2 4
0 3
1 4
0 4
[375, 250, 125, 0, 0]
[375, 250, 125, 0, 0]
135 Degree Diagonal Projection: [0, 0, 125, 250, 375, 250, 125, 0, 0]


In [70]:
min_135_diag = -len(arr)+1

d135_p_temp = [[] for _ in range(len(arr)+len(arr[0])-1)]

for i in range(len(arr)):
    for j in range(len(arr[i])):
        d135_p_temp[i-j-min_135_diag].append(arr[i][j])
        
d135_p_temp

[[0], [0, 0], [0, 125, 0], [0, 125, 125, 0], [0, 125, 0], [0, 0], [0]]

# Q1

In [14]:
row_back = np.zeros((len(arr), len(arr[0])), dtype='int')

for i in range(len(row_back)):
    row_back[i] = r_p[i]

row_back

array([[  0,   0,   0,   0,   0],
       [375, 375, 375, 375, 375],
       [375, 375, 375, 375, 375],
       [375, 375, 375, 375, 375],
       [  0,   0,   0,   0,   0]])

# Q2

In [15]:
col_back = np.copy(row_back)

for i in range(len(arr)):
    for j in range(len(arr[i])):
        col_back[i][j] += c_p[j]

col_back

array([[  0, 375, 375, 375,   0],
       [375, 750, 750, 750, 375],
       [375, 750, 750, 750, 375],
       [375, 750, 750, 750, 375],
       [  0, 375, 375, 375,   0]])

# Q3

In [16]:
d45_back = np.copy(col_back)

for i in range(len(arr)):
    for j in range(len(arr[i])):
        d45_back[i][j] += d45_p[i+j]

d45_back

array([[   0,  375,  500,  625,  375],
       [ 375,  875, 1000, 1125,  625],
       [ 500, 1000, 1125, 1000,  500],
       [ 625, 1125, 1000,  875,  375],
       [ 375,  625,  500,  375,    0]])

# Q4

In [17]:
d135_back = np.copy(d45_back)

min_135_diag = -len(arr)+1

for i in range(len(arr)):
    for j in range(len(arr[i])):
        d135_back[i][j] += d135_p[i-j-min_135_diag]

d135_back

array([[ 375,  625,  625,  625,  375],
       [ 625, 1250, 1250, 1250,  625],
       [ 625, 1250, 1500, 1250,  625],
       [ 625, 1250, 1250, 1250,  625],
       [ 375,  625,  625,  625,  375]])

In [18]:
len(arr)//2+1

3