In [1]:
import cv2
import numpy as np
from skimage.util import random_noise
from matplotlib import pyplot as plt
import statistics

In [2]:
img = cv2.imread("Lena.png")

cv2.imshow("Original", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Converting to gray scale

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [4]:
# Adding noise to images

def add_sp_noise(img, amt):
    noise_img = random_noise(img, mode='s&p',amount=amt)
    noise_img = np.array(255*noise_img, dtype = 'uint8')
    
    return noise_img

In [5]:
noise_img1 = add_sp_noise(gray, 0.1)
noise_img2 = add_sp_noise(gray, 0.2)
noise_img3 = add_sp_noise(gray, 0.3)
noise_img4 = add_sp_noise(gray, 0.4)
noise_img5 = add_sp_noise(gray, 0.5)
noise_img6 = add_sp_noise(gray, 0.6)
noise_img7 = add_sp_noise(gray, 0.7)
noise_img8 = add_sp_noise(gray, 0.8)
noise_img9 = add_sp_noise(gray, 0.9)
noise_img10 = add_sp_noise(gray, 1.0)

cv2.imshow("Original", gray)
cv2.imshow("noise_img1", noise_img1)
cv2.imshow("noise_img2", noise_img2)
cv2.imshow("noise_img3", noise_img3)
cv2.imshow("noise_img4", noise_img4)
cv2.imshow("noise_img5", noise_img5)
cv2.imshow("noise_img6", noise_img6)
cv2.imshow("noise_img7", noise_img7)
cv2.imshow("noise_img8", noise_img8)
cv2.imshow("noise_img9", noise_img9)
cv2.imshow("noise_img10", noise_img10)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Q1

In [6]:
# Creating filters

# 3X3
filter3 = np.ones((3,3))
filter3 = filter3/9

# 5X5
filter5 = np.ones((5,5))
filter5 = filter5/25

# 7X7
filter7 = np.ones((7,7))
filter7 = filter7/49


print(filter3)
print(filter5)
print(filter7)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
[[0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]]


In [7]:
noise_img1.shape

(512, 512)

In [ ]:
# padding zeroes to images

# new_img = np.zeros((noise_img1.shape[0]+filter3.shape[0]-1, noise_img1.shape[1]+filter3.shape[1]-1))

a = (filter3.shape[0]-1)//2
b = (filter3.shape[1]-1)//2

new_img = np.zeros((noise_img1.shape[0]+2*a+2*a, noise_img1.shape[1]+2*b+2*b), dtype=int)


for i in range(2*a, noise_img1.shape[0]+2*a):
    for j in range(2*b, noise_img1.shape[1]+2*b):
        new_img[i, j] = noise_img1[i-filter3.shape[0]+1, j-filter3.shape[1]+1]

print(new_img)
print(new_img.shape)

# a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# a[-1, -1]

In [ ]:
new_img1 = np.zeros((5+2*3+2*3, 5+2*3+2*3))

print(new_img1)
print(new_img1.shape)

for i in range(2*3, 5+2*3):
    for j in range(2*3, 5+2*3):
        print(i,j, i-7+1, j-7+1)

In [8]:
# Function to padd zeros
def pad_zeros(img_given, filter_given):
    a = (filter_given.shape[0]-1)//2
    b = (filter_given.shape[1]-1)//2
    
    new_img = np.zeros((img_given.shape[0]+2*a+2*a, img_given.shape[1]+2*b+2*b), dtype=int)
    
    for i in range(2*a, img_given.shape[0]+2*a):
        for j in range(2*b, img_given.shape[1]+2*b):
            new_img[i, j] = img_given[i-filter_given.shape[0]+1, j-filter_given.shape[1]+1]
    
    new_img = np.array(new_img, dtype='uint8')
    return new_img

In [9]:
new_img1 = pad_zeros(noise_img1, filter3)
new_img2 = pad_zeros(noise_img2, filter3)
new_img3 = pad_zeros(noise_img3, filter3)
new_img4 = pad_zeros(noise_img4, filter3)
new_img5 = pad_zeros(noise_img5, filter3)
new_img6 = pad_zeros(noise_img6, filter3)
new_img7 = pad_zeros(noise_img7, filter3)
new_img8 = pad_zeros(noise_img8, filter3)
new_img9 = pad_zeros(noise_img9, filter3)
new_img10 = pad_zeros(noise_img10, filter3)

print(new_img2)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 162 ... 128   0   0]
 ...
 [  0   0  44 ... 108   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [10]:
print(new_img2[2:511, 2:511])

[[162 162 162 ... 168 170 171]
 [162   0 162 ... 168 170 171]
 [162 162 162 ... 168 170 171]
 ...
 [ 48  48  56 ...   0  78   0]
 [ 54  54  48 ...  83 255  89]
 [ 46  46  50 ...  89  93 100]]


In [11]:
# output_img1 = np.zeros((noise_img1.shape[0]+filter3.shape[0]-1, noise_img1.shape[1]+filter3.shape[1]-1), dtype=int)

# for i in range(noise_img1.shape[0]+filter3.shape[0]-1):
#     for j in range(noise_img1.shape[1]+filter3.shape[1]-1):
#         output_img1[i, j]=(new_img1[i, j]*filter3[0, 0] + new_img1[i, j+1]*filter3[0, 1] + new_img1[i, j+2]*filter3[0, 2]) \
#         + (new_img1[i+1, j]*filter3[1, 0] + new_img1[i+1, j+1]*filter3[1, 1] + new_img1[i+1, j+2]*filter3[1, 2]) \
#         + (new_img1[i+2, j]*filter3[2, 0] + new_img1[i+2, j+1]*filter3[2, 1] + new_img1[i+2, j+2]*filter3[2, 2])

# print(output_img1)

output_img1 = np.zeros((noise_img1.shape[0]+filter3.shape[0]-1, noise_img1.shape[1]+filter3.shape[1]-1), dtype=int)

for i in range(noise_img1.shape[0]+filter3.shape[0]-1):
    for j in range(noise_img1.shape[1]+filter3.shape[1]-1):
        
        for k in range(0, 2*1+1):
            for l in range(0, 2*1+1):
                output_img1[i, j] += new_img1[i+k, j+l]*filter3[k, l]

print(output_img1)

[[ 18  36  36 ...  49  31  14]
 [ 36  54  72 ... 109  73  28]
 [ 54 100 136 ... 158 104  42]
 ...
 [ 60  72  89 ... 100  67  34]
 [ 32  40  52 ...  68  46  24]
 [  4   8  14 ...  34  23  12]]


In [12]:
# print(output_img1.shape)
output_img1 = np.array(output_img1, dtype='uint8')

cv2.imshow("Original1", noise_img1)
cv2.imshow("Original", output_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
def avg_filtering(noisy_img, padded_img, filter_gi):
    output_img1 = np.zeros((noisy_img.shape[0]+filter_gi.shape[0]-1, noisy_img.shape[1]+filter_gi.shape[1]-1), dtype=int)
    a = (filter_gi.shape[0]-1)//2
    b = (filter_gi.shape[1]-1)//2
    for i in range(noisy_img.shape[0]+filter_gi.shape[0]-1):
        for j in range(noisy_img.shape[1]+filter_gi.shape[1]-1):
            for k in range(0, 2*a+1):
                for l in range(0, 2*b+1):
                    output_img1[i, j] += padded_img[i+k, j+l]*filter_gi[k, l]
#             output_img1[i, j] = (padded_img[i, j]*filter_gi[0, 0] + padded_img[i, j+1]*filter_gi[0, 1] + padded_img[i, j+2]*filter_gi[0, 2]) \
#             + (padded_img[i+1, j]*filter_gi[1, 0] + padded_img[i+1, j+1]*filter_gi[1, 1] + padded_img[i+1, j+2]*filter_gi[1, 2]) \
#             + (padded_img[i+2, j]*filter_gi[2, 0] + padded_img[i+2, j+1]*filter_gi[2, 1] + padded_img[i+2, j+2]*filter_gi[2, 2])
    
    output_img1 = np.array(output_img1, dtype='uint8')
    
    return output_img1
    

In [14]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images = [new_img1, new_img2, new_img3, new_img4, new_img5, new_img6, new_img7, new_img8, new_img9, new_img10]

output_images = []

for i in range(len(noisy_images)):
    output_images.append(avg_filtering(noisy_images[i], padded_images[i], filter3))

In [15]:
for i in range(len(output_images)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images[i])
    title = "3x3 filter noisy image "+str(i+1) + " .jpg"
    cv2.imwrite(title, output_images[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
# 3x3 average filter done

In [14]:
a = (filter5.shape[0]-1)//2
b = (filter5.shape[1]-1)//2

new_img51 = np.zeros((noise_img1.shape[0]+2*a+2*a, noise_img1.shape[1]+2*b+2*b), dtype=int)


for i in range(2*a, noise_img1.shape[0]+2*a):
    for j in range(2*b, noise_img1.shape[1]+2*b):
#         print(i, j, i-7+1, j-7+1)
        new_img51[i, j] = noise_img1[i-filter5.shape[0]+1, j-filter5.shape[1]+1]

print(new_img51)
print(new_img51.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(520, 520)


In [15]:
output_img51 = np.zeros((noise_img1.shape[0]+filter5.shape[0]-1, noise_img1.shape[1]+filter5.shape[1]-1), dtype=int)

for i in range(noise_img1.shape[0]+filter5.shape[0]-1):
    for j in range(noise_img1.shape[1]+filter5.shape[1]-1):
        
        for k in range(0, 2*2+1):
            for l in range(0, 2*2+1):
                output_img51[i, j] += new_img51[i+k, j+l]*filter5[k, l]

print(output_img51)

[[ 6 12 18 ... 17 11  5]
 [12 24 36 ... 38 22 10]
 [18 36 54 ... 55 33 15]
 ...
 [ 3 15 21 ... 31 19 11]
 [ 2 13 17 ... 20 12  8]
 [ 1  2  4 ... 12  8  4]]


In [16]:
# print(output_img1.shape)
output_img51 = np.array(output_img51, dtype='uint8')

cv2.imshow("Original1", noise_img1)
cv2.imshow("Original", output_img51)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# FILTER 7X7
def pad_zeros(img_given, filter_given):
    a = (filter_given.shape[0]-1)//2
    b = (filter_given.shape[1]-1)//2
    
    new_img = np.zeros((img_given.shape[0]+2*a+2*a, img_given.shape[1]+2*b+2*b), dtype=int)
    
    for i in range(2*a, img_given.shape[0]+2*a):
        for j in range(2*b, img_given.shape[1]+2*b):
            new_img[i, j] = img_given[i-filter_given.shape[0]+1, j-filter_given.shape[1]+1]
    
    new_img = np.array(new_img, dtype='uint8')
    return new_img

new_img7_1 = pad_zeros(noise_img1, filter7)
new_img7_2 = pad_zeros(noise_img2, filter7)
new_img7_3 = pad_zeros(noise_img3, filter7)
new_img7_4 = pad_zeros(noise_img4, filter7)
new_img7_5 = pad_zeros(noise_img5, filter7)
new_img7_6 = pad_zeros(noise_img6, filter7)
new_img7_7 = pad_zeros(noise_img7, filter7)
new_img7_8 = pad_zeros(noise_img8, filter7)
new_img7_9 = pad_zeros(noise_img9, filter7)
new_img7_10 = pad_zeros(noise_img10, filter7)

# print(new_img7_1)
# print(new_img7_1.shape)

def avg_filtering(noisy_img, padded_img, filter_gi):
    output_img1 = np.zeros((noisy_img.shape[0]+filter_gi.shape[0]-1, noisy_img.shape[1]+filter_gi.shape[1]-1), dtype=int)
    a = (filter_gi.shape[0]-1)//2
    b = (filter_gi.shape[1]-1)//2
    for i in range(noisy_img.shape[0]+filter_gi.shape[0]-1):
        for j in range(noisy_img.shape[1]+filter_gi.shape[1]-1):
            for k in range(0, 2*a+1):
                for l in range(0, 2*b+1):
                    output_img1[i, j] += padded_img[i+k, j+l]*filter_gi[k, l]
            
    output_img1 = np.array(output_img1, dtype='uint8')
    
    return output_img1
    
    
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images7 = [new_img7_1, new_img7_2, new_img7_3, new_img7_4, new_img7_5, new_img7_6, new_img7_7, new_img7_8, new_img7_9, new_img7_10]

output_images7 = []

for i in range(len(noisy_images)):
    output_images7.append(avg_filtering(noisy_images[i], padded_images7[i], filter7))


KeyboardInterrupt: 

In [ ]:
for i in range(len(output_images7)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images7[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Median Filtering

In [ ]:
output_img3_1 = np.zeros((noise_img1.shape[0], noise_img1.shape[1]), dtype=int)

a = (filter3.shape[0]-1)//2
b = (filter3.shape[1]-1)//2

for i in range(noise_img1.shape[0]):
    for j in range(noise_img1.shape[1]):
        
        list_neigh = []
        if(i==0 and j==0):
            list_neigh = [noise_img1[i, j], noise_img1[i, j+1], noise_img1[i+1, j], noise_img1[i+1, j+1]]
            list_neigh = sorted(list_neigh)
            output_img3_1[i, j] = int(statistics.median(list_neigh))
        elif(i==0 and j==noise_img1.shape[1]-1):
            list_neigh = [noise_img1[i, j], noise_img1[i-1, j], noise_img1[i+1, j], noise_img1[i+1, j-1]]
            list_neigh = sorted(list_neigh)
            output_img3_1[i, j] = int(statistics.median(list_neigh))
        elif(i==noise_img1.shape[0]-1 and j==0):
            list_neigh = [noise_img1[i, j], noise_img1[i, j+1], noise_img1[i-1, j], noise_img1[i-1, j+1]]
            list_neigh = sorted(list_neigh)
            output_img3_1[i, j] = int(statistics.median(list_neigh))
        elif(i==noise_img1.shape[0]-1 and j==noise_img1.shape[1]-1):
            list_neigh = [noise_img1[i, j], noise_img1[i, j-1], noise_img1[i-1, j], noise_img1[i-1, j-1]]
            list_neigh = sorted(list_neigh)
            output_img3_1[i, j] = int(statistics.median(list_neigh))
        elif(i==0 and j!=0):
            
            
print(output_img1)

In [25]:
# Function to padd zeros
def pad_zeros(img_given, filter_given):
    a = (filter_given.shape[0]-1)//2
    b = (filter_given.shape[1]-1)//2
    
    new_img = np.zeros((img_given.shape[0]+2*a+2*a, img_given.shape[1]+2*b+2*b), dtype=int)
    
    for i in range(2*a, img_given.shape[0]+2*a):
        for j in range(2*b, img_given.shape[1]+2*b):
            new_img[i, j] = img_given[i-filter_given.shape[0]+1, j-filter_given.shape[1]+1]
    
    new_img = np.array(new_img, dtype='uint8')
    return new_img

In [26]:
new_img1 = pad_zeros(noise_img1, filter3)
new_img2 = pad_zeros(noise_img2, filter3)
new_img3 = pad_zeros(noise_img3, filter3)
new_img4 = pad_zeros(noise_img4, filter3)
new_img5 = pad_zeros(noise_img5, filter3)
new_img6 = pad_zeros(noise_img6, filter3)
new_img7 = pad_zeros(noise_img7, filter3)
new_img8 = pad_zeros(noise_img8, filter3)
new_img9 = pad_zeros(noise_img9, filter3)
new_img10 = pad_zeros(noise_img10, filter3)

print(new_img2)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 162 ... 128   0   0]
 ...
 [  0   0  44 ... 108   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [27]:
def median_filtering(noisy_img, padded_img, filter_gi):
    output_img1 = np.zeros((noisy_img.shape[0]+filter_gi.shape[0]-1, noisy_img.shape[1]+filter_gi.shape[1]-1), dtype=int)
    a = (filter_gi.shape[0]-1)//2
    b = (filter_gi.shape[1]-1)//2
    
    for i in range(noisy_img.shape[0]+filter_gi.shape[0]-1):
        for j in range(noisy_img.shape[1]+filter_gi.shape[1]-1):
            
            list_neigh = []
            for k in range(0, 2*a+1):
                for l in range(0, 2*b+1):
                    list_neigh.append(padded_img[i+k, j+l])
                    # output_img1[i, j] += padded_img[i+k, j+l]*filter_gi[k, l]
            
            list_neigh = sorted(list_neigh)
            output_img1[i, j] = int(statistics.median(list_neigh))

    output_img1 = np.array(output_img1, dtype='uint8')
    
    return output_img1
    

In [29]:
out1 = median_filtering(noise_img1, new_img1, filter3)

In [30]:
cv2.imshow("Original1", noise_img1)
cv2.imshow("Original", out1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images = [new_img1, new_img2, new_img3, new_img4, new_img5, new_img6, new_img7, new_img8, new_img9, new_img10]

output_images = []

for i in range(len(noisy_images)):
    output_images.append(median_filtering(noisy_images[i], padded_images[i], filter3))

In [34]:
for i in range(len(output_images)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images[i])
#     title = "3x3 median filter "+str(i+1) + " .jpg"
#     cv2.imwrite(title, output_images[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

new_a = np.zeros((a.shape[0]+2*1, a.shape[1]+2*1), dtype=int)

new_a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])