In [1]:
import cv2
import numpy as np
from skimage.util import random_noise
from matplotlib import pyplot as plt
import statistics

In [2]:
img = cv2.imread("Lena.png")

cv2.imshow("Original", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Converting to gray scale

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [4]:
# Adding noise to images

def add_sp_noise(img, amt):
    noise_img = random_noise(img, mode='s&p',amount=amt)
    noise_img = np.array(255*noise_img, dtype = 'uint8')
    
    return noise_img

In [5]:
noise_img1 = add_sp_noise(gray, 0.1)
noise_img2 = add_sp_noise(gray, 0.2)
noise_img3 = add_sp_noise(gray, 0.3)
noise_img4 = add_sp_noise(gray, 0.4)
noise_img5 = add_sp_noise(gray, 0.5)
noise_img6 = add_sp_noise(gray, 0.6)
noise_img7 = add_sp_noise(gray, 0.7)
noise_img8 = add_sp_noise(gray, 0.8)
noise_img9 = add_sp_noise(gray, 0.9)
noise_img10 = add_sp_noise(gray, 1.0)

cv2.imshow("Original", gray)
cv2.imshow("noise_img1", noise_img1)
cv2.imshow("noise_img2", noise_img2)
cv2.imshow("noise_img3", noise_img3)
cv2.imshow("noise_img4", noise_img4)
cv2.imshow("noise_img5", noise_img5)
cv2.imshow("noise_img6", noise_img6)
cv2.imshow("noise_img7", noise_img7)
cv2.imshow("noise_img8", noise_img8)
cv2.imshow("noise_img9", noise_img9)
cv2.imshow("noise_img10", noise_img10)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Q1

In [6]:
# Creating filters

# 3X3
filter3 = np.ones((3,3))
filter3 = filter3/9

# 5X5
filter5 = np.ones((5,5))
filter5 = filter5/25

# 7X7
filter7 = np.ones((7,7))
filter7 = filter7/49


print(filter3)
print(filter5)
print(filter7)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
[[0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]]


In [7]:
# Padding Zeros function
def pad_zeros(img_given, filter_given):
    a = (filter_given.shape[0]-1)//2
    b = (filter_given.shape[1]-1)//2
    
    new_img = np.zeros((img_given.shape[0]+2*a+2*a, img_given.shape[1]+2*b+2*b), dtype=int)
    
    for i in range(2*a, img_given.shape[0]+2*a):
        for j in range(2*b, img_given.shape[1]+2*b):
            new_img[i, j] = img_given[i-filter_given.shape[0]+1, j-filter_given.shape[1]+1]
    
    new_img = np.array(new_img, dtype='uint8')
    return new_img

In [8]:
def avg_filtering(noisy_img, padded_img, filter_gi):
    output_img1 = np.zeros((noisy_img.shape[0]+filter_gi.shape[0]-1, noisy_img.shape[1]+filter_gi.shape[1]-1), dtype=int)
    a = (filter_gi.shape[0]-1)//2
    b = (filter_gi.shape[1]-1)//2
    
    for i in range(noisy_img.shape[0]+filter_gi.shape[0]-1):
        for j in range(noisy_img.shape[1]+filter_gi.shape[1]-1):
            for k in range(0, 2*a+1):
                for l in range(0, 2*b+1):
                    output_img1[i, j] += padded_img[i+k, j+l]*filter_gi[k, l]
#             output_img1[i, j] = (padded_img[i, j]*filter_gi[0, 0] + padded_img[i, j+1]*filter_gi[0, 1] + padded_img[i, j+2]*filter_gi[0, 2]) \
#             + (padded_img[i+1, j]*filter_gi[1, 0] + padded_img[i+1, j+1]*filter_gi[1, 1] + padded_img[i+1, j+2]*filter_gi[1, 2]) \
#             + (padded_img[i+2, j]*filter_gi[2, 0] + padded_img[i+2, j+1]*filter_gi[2, 1] + padded_img[i+2, j+2]*filter_gi[2, 2])
    
    output_img1 = np.array(output_img1, dtype='uint8')
    
    return output_img1

3x3 filter

In [9]:
new_img3_1 = pad_zeros(noise_img1, filter3)
new_img3_2 = pad_zeros(noise_img2, filter3)
new_img3_3 = pad_zeros(noise_img3, filter3)
new_img3_4 = pad_zeros(noise_img4, filter3)
new_img3_5 = pad_zeros(noise_img5, filter3)
new_img3_6 = pad_zeros(noise_img6, filter3)
new_img3_7 = pad_zeros(noise_img7, filter3)
new_img3_8 = pad_zeros(noise_img8, filter3)
new_img3_9 = pad_zeros(noise_img9, filter3)
new_img3_10 = pad_zeros(noise_img10, filter3)

print(new_img3_2)

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 162 ... 128   0   0]
 ...
 [  0   0  44 ... 108   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [10]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_3 = [new_img3_1, new_img3_2, new_img3_3, new_img3_4, new_img3_5, new_img3_6, new_img3_7, new_img3_8, new_img3_9, new_img3_10]

output_images_3 = []

for i in range(len(noisy_images)):
    output_images_3.append(avg_filtering(noisy_images[i], padded_images_3[i], filter3))

In [29]:
for i in range(len(output_images_3)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images_3[i])
    title = "3x3 filter noisy image "+str(i+1) + " .jpg"
    cv2.imwrite(title, output_images_3[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

5x5 filter

In [12]:
new_img5_1 = pad_zeros(noise_img1, filter5)
new_img5_2 = pad_zeros(noise_img2, filter5)
new_img5_3 = pad_zeros(noise_img3, filter5)
new_img5_4 = pad_zeros(noise_img4, filter5)
new_img5_5 = pad_zeros(noise_img5, filter5)
new_img5_6 = pad_zeros(noise_img6, filter5)
new_img5_7 = pad_zeros(noise_img7, filter5)
new_img5_8 = pad_zeros(noise_img8, filter5)
new_img5_9 = pad_zeros(noise_img9, filter5)
new_img5_10 = pad_zeros(noise_img10, filter5)

print(new_img5_2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_5 = [new_img5_1, new_img5_2, new_img5_3, new_img5_4, new_img5_5, new_img5_6, new_img5_7, new_img5_8, new_img5_9, new_img5_10]

output_images_5 = []

for i in range(len(noisy_images)):
    output_images_5.append(avg_filtering(noisy_images[i], padded_images_5[i], filter5))

In [30]:
for i in range(len(output_images_5)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images_5[i])
    title = "5x5 filter noisy image "+str(i+1) + " .jpg"
    cv2.imwrite(title, output_images_5[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

7x7 filter

In [15]:
new_img7_1 = pad_zeros(noise_img1, filter7)
new_img7_2 = pad_zeros(noise_img2, filter7)
new_img7_3 = pad_zeros(noise_img3, filter7)
new_img7_4 = pad_zeros(noise_img4, filter7)
new_img7_5 = pad_zeros(noise_img5, filter7)
new_img7_6 = pad_zeros(noise_img6, filter7)
new_img7_7 = pad_zeros(noise_img7, filter7)
new_img7_8 = pad_zeros(noise_img8, filter7)
new_img7_9 = pad_zeros(noise_img9, filter7)
new_img7_10 = pad_zeros(noise_img10, filter7)

print(new_img7_2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_7 = [new_img7_1, new_img7_2, new_img7_3, new_img7_4, new_img7_5, new_img7_6, new_img7_7, new_img7_8, new_img7_9, new_img7_10]

output_images_7 = []

for i in range(len(noisy_images)):
    output_images_7.append(avg_filtering(noisy_images[i], padded_images_7[i], filter7))

In [31]:
for i in range(len(output_images_7)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", output_images_7[i])
    title = "7x7 filter noisy image "+str(i+1) + " .jpg"
    cv2.imwrite(title, output_images_7[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [32]:
# inbuilt function
blur = cv2.blur(noise_img1,(3,3))
cv2.imshow("Inbuilt", blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Q2

In [18]:
def median_filtering(noisy_img, padded_img, filter_gi):
    output_img1 = np.zeros((noisy_img.shape[0]+filter_gi.shape[0]-1, noisy_img.shape[1]+filter_gi.shape[1]-1), dtype=int)
    a = (filter_gi.shape[0]-1)//2
    b = (filter_gi.shape[1]-1)//2
    
    for i in range(noisy_img.shape[0]+filter_gi.shape[0]-1):
        for j in range(noisy_img.shape[1]+filter_gi.shape[1]-1):
            
            list_neigh = []
            for k in range(0, 2*a+1):
                for l in range(0, 2*b+1):
                    list_neigh.append(padded_img[i+k, j+l])
                    # output_img1[i, j] += padded_img[i+k, j+l]*filter_gi[k, l]
            
            list_neigh = sorted(list_neigh)
            output_img1[i, j] = int(statistics.median(list_neigh))

    output_img1 = np.array(output_img1, dtype='uint8')
    
    return output_img1

3x3 filter

In [19]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_3 = [new_img3_1, new_img3_2, new_img3_3, new_img3_4, new_img3_5, new_img3_6, new_img3_7, new_img3_8, new_img3_9, new_img3_10]

m_output_images_3 = []

for i in range(len(noisy_images)):
    m_output_images_3.append(median_filtering(noisy_images[i], padded_images_3[i], filter3))

In [33]:
for i in range(len(m_output_images_3)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", m_output_images_3[i])
    title = "3x3 median filter "+str(i+1) + " .jpg"
    cv2.imwrite(title, m_output_images_3[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

5x5 filter

In [21]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_5 = [new_img5_1, new_img5_2, new_img5_3, new_img5_4, new_img5_5, new_img5_6, new_img5_7, new_img5_8, new_img5_9, new_img5_10]

m_output_images_5 = []

for i in range(len(noisy_images)):
    m_output_images_5.append(median_filtering(noisy_images[i], padded_images_5[i], filter5))

In [22]:
for i in range(len(m_output_images_5)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", m_output_images_5[i])
    title = "5x5 median filter "+str(i+1) + " .jpg"
    cv2.imwrite(title, m_output_images_5[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

7x7 filter

In [23]:
noisy_images = [noise_img1, noise_img2, noise_img3, noise_img4, noise_img5, noise_img6, noise_img7, noise_img8, noise_img9, noise_img10]
padded_images_7 = [new_img7_1, new_img7_2, new_img7_3, new_img7_4, new_img7_5, new_img7_6, new_img7_7, new_img7_8, new_img7_9, new_img7_10]

m_output_images_7 = []

for i in range(len(noisy_images)):
    m_output_images_7.append(median_filtering(noisy_images[i], padded_images_7[i], filter7))

In [34]:
for i in range(len(m_output_images_7)):
    cv2.imshow("Original1", noisy_images[i])
    cv2.imshow("Original", m_output_images_7[i])
    title = "7x7 median filter "+str(i+1) + " .jpg"
    cv2.imwrite(title, m_output_images_7[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [35]:
# inbuilt function
median_blur = cv2.medianBlur(noise_img1, 3)
cv2.imshow("Inbuilt", median_blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.medianBlur(img,5)
cv2.blur(img,(5,5))